# Generated by Django 5.2.1 on 2025-05-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_rename_type_livraison_commande_type_livraison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Commune',
        ),
    ]
