# Generated by Django 5.2.1 on 2025-05-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_remove_commande_prix_livraison_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='Bureau',
            new_name='commune',
        ),
    ]
