# Generated by Django 5.2.1 on 2025-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_rename_bureau_commande_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
