# Generated by Django 5.2.1 on 2025-06-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_commande_prix_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat_commande',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Livrée', 'Livrée'), ('Retour', 'Retour')], default='En attente', max_length=30),
        ),
    ]
