# Generated by Django 5.2.1 on 2025-05-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_rename_user_gestionnaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gestionnaire',
        ),
    ]
