# Generated by Django 5.2.1 on 2025-06-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_produit_prix_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='liste_produits',
        ),
    ]
