# Generated by Django 5.2.1 on 2025-05-26 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id_livraison', models.AutoField(primary_key=True, serialize=False)),
                ('Type_livraison', models.CharField(choices=[('Bureau', 'Bureau'), ('Domicile', 'Domicile')], default='Bureau', max_length=30)),
                ('Adresse_livraison', models.CharField(blank=True, max_length=255, null=True)),
                ('Wilaya', models.CharField(blank=True, choices=[('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oum El Bouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Béjaïa'), ('Biskra', 'Biskra'), ('Béchar', 'Béchar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saïda', 'Saïda'), ('Skikda', 'Skikda'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ("M'Sila", "M'Sila"), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Boumerdes', 'Boumerdes'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Aïn Defla', 'Aïn Defla'), ('Naama', 'Naama'), ('Aïn Témouchent', 'Aïn Témouchent'), ('Ghardaia', 'Ghardaia'), ('Relizane', 'Relizane'), ('Timimoun', 'Timimoun'), ('Bordj Badji Mokhtar', 'Bordj Badji Mokhtar'), ('Ouled Djellal', 'Ouled Djellal'), ('Béni Abbès', 'Béni Abbès'), ('In Salah', 'In Salah'), ('In Guezzam', 'In Guezzam'), ('Touggourt', 'Touggourt'), ('Djanet', 'Djanet'), ("El M'Ghair", "El M'Ghair"), ('El Menia', 'El Menia')], max_length=100, null=True)),
                ('Commune', models.CharField(blank=True, max_length=255, null=True)),
                ('Bureau', models.CharField(blank=True, max_length=255, null=True)),
                ('Prix_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField(default=django.utils.timezone.now)),
                ('quantite_commandé', models.IntegerField(default=1)),
                ('etat_commande', models.CharField(choices=[('En attente', 'En attente'), ('En cours de traitement', 'En cours de traitement'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=30)),
                ('nom_client', models.CharField(max_length=100)),
                ('numero_client', models.CharField(max_length=15)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('produit_commandé', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_commandé', to='Products.variant')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='Orders.livraison')),
            ],
        ),
    ]
