# Generated by Django 5.2.1 on 2025-06-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commande',
            name='Orders_comm_date_co_dec884_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='Orders_comm_etat_co_ff77ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='Orders_comm_produit_006477_idx',
        ),
    ]
