# Generated by Django 5.2.1 on 2025-06-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_remove_commande_orders_comm_date_co_dec884_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Bureau_Yalidine',
            field=models.CharField(blank=True, default=None, help_text='Bureau Yalidine pour livraison en bureau', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='Bureau_ZD',
            field=models.CharField(blank=True, default=None, help_text='Bureau ZD pour livraison en bureau', max_length=255, null=True),
        ),
    ]
