# Generated by Django 5.2.1 on 2025-06-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_commande_bureau_yalidine_commande_bureau_zd'),
        ('Products', '0012_variant_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit_commandé',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite_commandé',
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Orders.commande')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.variant')),
            ],
        ),
    ]
