# Generated by Django 5.2.1 on 2025-06-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_remove_commande_produit_commandé_and_more'),
        ('Products', '0012_variant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Orders.commande')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.couleur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.produit')),
                ('taille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.taille')),
            ],
            options={
                'unique_together': {('commande', 'produit', 'couleur', 'taille')},
            },
        ),
        migrations.DeleteModel(
            name='LigneCommande',
        ),
    ]
