# Generated by Django 5.2.1 on 2025-06-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_produitcommande_delete_lignecommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Bureau_Yalidine',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='Bureau_ZD',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produitcommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='Orders.commande'),
        ),
    ]
