# Generated by Django 5.2.1 on 2025-06-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_commande_bureau_yalidine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='Bureau_ZD',
            new_name='Bureau_ZR',
        ),
    ]
