# Generated by Django 5.2.1 on 2025-06-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaires', '0001_initial'),
        ('Products', '0011_remove_boutique_liste_produits_produit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionnaire',
            name='boutique',
            field=models.ManyToManyField(blank=True, related_name='user_boutique', to='Products.boutique'),
        ),
    ]
