# Generated by Django 5.2.1 on 2025-05-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionnaire',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='user_permissions',
        ),
    ]
