# Generated by Django 5.2.1 on 2025-05-26 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id_couleur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_couleur', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=30)),
                ('prix_produit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descreption_produit', models.TextField(blank=True)),
                ('categorie_produit', models.CharField(blank=True, max_length=30)),
                ('quantite_produit', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id_taille', models.AutoField(primary_key=True, serialize=False)),
                ('nom_taille', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id_variant', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0)),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_couleur_taille', to='Products.couleur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_couleur_taille', to='Products.produit')),
                ('taille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_couleur_taille', to='Products.taille')),
            ],
        ),
    ]
