# Generated by Django 5.2.1 on 2025-05-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
