# Generated by Django 5.2.1 on 2025-05-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_variant_quantite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('produit', 'couleur', 'taille')},
        ),
    ]
