# Generated by Django 5.2.1 on 2025-05-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_variant_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id_boutique', models.AutoField(primary_key=True, serialize=False)),
                ('nom_boutique', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='Products.boutique'),
        ),
    ]
