# Generated by Django 5.2.1 on 2025-05-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_boutique_produit_boutique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie_produit',
        ),
    ]
