# Generated by Django 5.2.1 on 2025-05-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_produit_categorie_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='liste_produit',
            field=models.ManyToManyField(blank=True, related_name='boutiques', to='Products.produit'),
        ),
    ]
