# Generated by Django 5.2.1 on 2025-05-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_boutique_liste_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boutique',
            old_name='liste_produit',
            new_name='liste_produits',
        ),
    ]
