# Generated by Django 5.2.1 on 2025-06-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_rename_user_gestionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='liste_produits',
        ),
        migrations.AddField(
            model_name='produit',
            name='ID',
            field=models.CharField(default='0', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='Products.boutique'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_produit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variant',
            name='couleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produit_couleur_taille', to='Products.couleur'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produit_couleur_taille', to='Products.produit'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='taille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produit_couleur_taille', to='Products.taille'),
        ),
        migrations.DeleteModel(
            name='Gestionnaire',
        ),
    ]
