# Generated by Django 5.2.1 on 2025-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_delete_gestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_produit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
