# Generated by Django 5.2.1 on 2025-06-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_remove_boutique_liste_produits_produit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='SKU',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
